name:simple CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  simple_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run simple command
        run: echo "Hello, World! This is a simple CI pipeline."

      - name: Send notification
        run: echo "Pipeline completed successfully!"
